
import java.sql.*;
import java.time.LocalDate;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ishaa
 */
public class AppointmentBooking extends javax.swing.JFrame {
    int PatientID;
    /**
     * Creates new form AppointmentBooking
     */
    public AppointmentBooking(int pid) {
        initComponents();
        PatientID = pid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepartmentRadio = new javax.swing.ButtonGroup();
        when = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdoCardiology = new javax.swing.JRadioButton();
        rdoOrthopedics = new javax.swing.JRadioButton();
        rdoPediatrics = new javax.swing.JRadioButton();
        rdoNeurology = new javax.swing.JRadioButton();
        rdoOncology = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        reasonVisit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tomm = new javax.swing.JRadioButton();
        dayAfterTomm = new javax.swing.JRadioButton();
        book_app = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Book an Appointment");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Choose Department");

        DepartmentRadio.add(rdoCardiology);
        rdoCardiology.setText("Cardiology");

        DepartmentRadio.add(rdoOrthopedics);
        rdoOrthopedics.setText("Orthopedics");

        DepartmentRadio.add(rdoPediatrics);
        rdoPediatrics.setText("Pediatrics");

        DepartmentRadio.add(rdoNeurology);
        rdoNeurology.setText("Neurology");

        DepartmentRadio.add(rdoOncology);
        rdoOncology.setText("Oncology");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Reason For Visit");

        reasonVisit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("When");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        when.add(tomm);
        tomm.setText("Tomorrow");

        when.add(dayAfterTomm);
        dayAfterTomm.setText("Day-After Tomorrow");

        book_app.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        book_app.setText("Book");
        book_app.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_appActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 51));
        error.setText("   ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mobile Number");

        mobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mobile)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tomm)
                                            .addGap(18, 18, 18)
                                            .addComponent(dayAfterTomm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(book_app, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdoCardiology)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoOrthopedics)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoPediatrics)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoNeurology)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoOncology))
                                .addComponent(reasonVisit)))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdoCardiology)
                    .addComponent(rdoOrthopedics)
                    .addComponent(rdoPediatrics)
                    .addComponent(rdoNeurology)
                    .addComponent(rdoOncology))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reasonVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tomm)
                    .addComponent(dayAfterTomm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(book_app)
                .addGap(18, 18, 18)
                .addComponent(error)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void book_appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_appActionPerformed
        // TODO add your handling code here:
        try{
            int DoctorID;
            String reason;
            String date = "";
            String mobNo;
            if(rdoCardiology.isSelected()){
                DoctorID = 1;
            }
            else if(rdoOrthopedics.isSelected()){
                DoctorID = 2;
            }
            else if(rdoPediatrics.isSelected()){
                DoctorID = 3;
            }
            else if(rdoNeurology.isSelected()){
                DoctorID = 4;
            }
            else if(rdoOncology.isSelected()){
                DoctorID = 5;
            }
            else{
                error.setText("Please select department you want to visit");
                return;
            }
            
            reason = reasonVisit.getText();
            if(reason.isEmpty()){
                error.setText("Please fill Reason For Visit");
                return;
            }
            
            if(tomm.isSelected()){
                LocalDate when = LocalDate.now().plusDays(1);
                date = when.toString();
            }
            else if(dayAfterTomm.isSelected()){
                LocalDate when = LocalDate.now().plusDays(2);
                date = when.toString();
            }
            else{
                error.setText("Please Select When you want to schedule the visit");
            }
            
            mobNo = mobile.getText();
            if(mobNo.isEmpty() && mobNo.length() != 10){
                error.setText("Please enter correct mobile number");
                return;
            }
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital_Management", "root", "!shuB0410");
            Statement s = con.createStatement();
            String query = "INSERT INTO Appointments (Patient_ID, Doctor_ID, Reason_for_visit, date) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, PatientID);
            ps.setInt(2, DoctorID);
            ps.setString(3, reason);
            ps.setString(4, date);
            
            int rowsAffected = ps.executeUpdate();
            if(rowsAffected > 0){
                AppointmentBooked ab = new AppointmentBooked(PatientID, DoctorID, reason, date, mobNo);
                ab.setVisible(true);
                this.setVisible(false);
            }
            else{
                error.setText("Error during booking an appointment");
            }
            
            
        }
        catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_book_appActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AppointmentBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DepartmentRadio;
    private javax.swing.JButton book_app;
    private javax.swing.JRadioButton dayAfterTomm;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mobile;
    private javax.swing.JRadioButton rdoCardiology;
    private javax.swing.JRadioButton rdoNeurology;
    private javax.swing.JRadioButton rdoOncology;
    private javax.swing.JRadioButton rdoOrthopedics;
    private javax.swing.JRadioButton rdoPediatrics;
    private javax.swing.JTextField reasonVisit;
    private javax.swing.JRadioButton tomm;
    private javax.swing.ButtonGroup when;
    // End of variables declaration//GEN-END:variables
}
