
import java.sql.*;
import java.time.LocalDate;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ishaa
 */
public class AppointmentBooking extends javax.swing.JFrame {
    int PatientID;
    /**
     * Creates new form AppointmentBooking
     */
    public AppointmentBooking(int pid) {
        initComponents();
        PatientID = pid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepartmentRadio = new javax.swing.ButtonGroup();
        when = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdoCardiology = new javax.swing.JRadioButton();
        rdoOrthopedics = new javax.swing.JRadioButton();
        rdoPediatrics = new javax.swing.JRadioButton();
        rdoNeurology = new javax.swing.JRadioButton();
        rdoOncology = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        reasonVisit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tomm = new javax.swing.JRadioButton();
        dayAfterTomm = new javax.swing.JRadioButton();
        book_app = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(782, 320));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Book an Appointment");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 10, 210, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Choose Department");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 150, 20);

        DepartmentRadio.add(rdoCardiology);
        rdoCardiology.setText("Cardiology");
        getContentPane().add(rdoCardiology);
        rdoCardiology.setBounds(210, 50, 100, 21);

        DepartmentRadio.add(rdoOrthopedics);
        rdoOrthopedics.setText("Orthopedics");
        getContentPane().add(rdoOrthopedics);
        rdoOrthopedics.setBounds(310, 50, 90, 21);

        DepartmentRadio.add(rdoPediatrics);
        rdoPediatrics.setText("Pediatrics");
        getContentPane().add(rdoPediatrics);
        rdoPediatrics.setBounds(410, 50, 90, 21);

        DepartmentRadio.add(rdoNeurology);
        rdoNeurology.setText("Neurology");
        getContentPane().add(rdoNeurology);
        rdoNeurology.setBounds(510, 50, 90, 21);

        DepartmentRadio.add(rdoOncology);
        rdoOncology.setText("Oncology");
        getContentPane().add(rdoOncology);
        rdoOncology.setBounds(600, 50, 100, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Reason For Visit");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 170, 20);

        reasonVisit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(reasonVisit);
        reasonVisit.setBounds(210, 100, 260, 26);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("When");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 150, 130, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 150, 30, 0);

        when.add(tomm);
        tomm.setText("Tomorrow");
        getContentPane().add(tomm);
        tomm.setBounds(210, 150, 100, 21);

        when.add(dayAfterTomm);
        dayAfterTomm.setText("Day-After Tomorrow");
        getContentPane().add(dayAfterTomm);
        dayAfterTomm.setBounds(310, 150, 160, 21);

        book_app.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        book_app.setText("Book");
        book_app.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_appActionPerformed(evt);
            }
        });
        getContentPane().add(book_app);
        book_app.setBounds(210, 230, 260, 32);

        error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 51));
        error.setText("   ");
        getContentPane().add(error);
        error.setBounds(210, 210, 690, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 180, 160, 20);

        mobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(mobile);
        mobile.setBounds(210, 180, 260, 26);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OIP (2).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1041, 650));
        jLabel7.setMinimumSize(new java.awt.Dimension(1041, 650));
        jLabel7.setPreferredSize(new java.awt.Dimension(1041, 650));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-90, 0, 890, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void book_appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_appActionPerformed
        // TODO add your handling code here:
        try{
            int DoctorID;
            String reason;
            String date = "";
            String mobNo;
            if(rdoCardiology.isSelected()){
                DoctorID = 1;
            }
            else if(rdoOrthopedics.isSelected()){
                DoctorID = 2;
            }
            else if(rdoPediatrics.isSelected()){
                DoctorID = 3;
            }
            else if(rdoNeurology.isSelected()){
                DoctorID = 4;
            }
            else if(rdoOncology.isSelected()){
                DoctorID = 5;
            }
            else{
                error.setText("Please select department you want to visit");
                return;
            }
            
            reason = reasonVisit.getText();
            if(reason.isEmpty()){
                error.setText("Please fill Reason For Visit");
                return;
            }
            
            if(tomm.isSelected()){
                LocalDate when = LocalDate.now().plusDays(1);
                date = when.toString();
            }
            else if(dayAfterTomm.isSelected()){
                LocalDate when = LocalDate.now().plusDays(2);
                date = when.toString();
            }
            else{
                error.setText("Please Select When you want to schedule the visit");
            }
            
            mobNo = mobile.getText();
            if(mobNo.isEmpty() && mobNo.length() != 10){
                error.setText("Please enter correct mobile number");
                return;
            }
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital_Management", "root", "!shuB0410");
            Statement s = con.createStatement();
            String query = "INSERT INTO Appointments (Patient_ID, Doctor_ID, Reason_for_visit, date) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, PatientID);
            ps.setInt(2, DoctorID);
            ps.setString(3, reason);
            ps.setString(4, date);
            
            int rowsAffected = ps.executeUpdate();
            if(rowsAffected > 0){
                AppointmentBooked ab = new AppointmentBooked(PatientID, DoctorID, reason, date, mobNo);
                ab.setVisible(true);
                this.setVisible(false);
            }
            else{
                error.setText("Error during booking an appointment");
            }
            
            
        }
        catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_book_appActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AppointmentBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DepartmentRadio;
    private javax.swing.JButton book_app;
    private javax.swing.JRadioButton dayAfterTomm;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mobile;
    private javax.swing.JRadioButton rdoCardiology;
    private javax.swing.JRadioButton rdoNeurology;
    private javax.swing.JRadioButton rdoOncology;
    private javax.swing.JRadioButton rdoOrthopedics;
    private javax.swing.JRadioButton rdoPediatrics;
    private javax.swing.JTextField reasonVisit;
    private javax.swing.JRadioButton tomm;
    private javax.swing.ButtonGroup when;
    // End of variables declaration//GEN-END:variables
}
