/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
/**
 *
 * @author ishaa
 */
public class AppointmentBooked extends javax.swing.JFrame {
    int patientid;
    int doctorid;
    String Reason;
    String Date;
    String Mobile;
    
    /**
     * Creates new form AppointmentBooked
     */
    public AppointmentBooked(int pid, int did, String re, String date, String mb) {
        initComponents();
        patientid = pid;
        doctorid = did;
        Reason = re;
        Date = date;
        Mobile = mb;
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital_Management", "root", "!shuB0410");
            Statement s = con.createStatement();
            String DoctorName = "";
            ResultSet rs = s.executeQuery("SELECT name FROM Staff WHERE Staff_ID=" + doctorid);
            if(rs.next()){
                DoctorName = rs.getString("Name");
            }
            
            details.setText("<html>Patient ID: " + patientid + "<br>"
                        + "Doctor Name: " + DoctorName + "<br>"
                        + "Reason for Visit: " + Reason + "<br>"
                        + "Date: " + Date + "</html>");
        }
        catch(Exception e){
            System.out.println(e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        return_menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(398, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Appointment Booked");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(115, 25, 200, 25);

        details.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        details.setText("jLabel2");
        getContentPane().add(details);
        details.setBounds(100, 60, 290, 192);

        return_menu.setText("Return To Menu");
        return_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_menuActionPerformed(evt);
            }
        });
        getContentPane().add(return_menu);
        return_menu.setBounds(110, 260, 185, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OIP (2).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -30, 470, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_menuActionPerformed
        // TODO add your handling code here:
        PatientMenu pm = new PatientMenu(patientid);
        pm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_return_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentBooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AppointmentBooked().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton return_menu;
    // End of variables declaration//GEN-END:variables
}
