/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
/**
 *
 * @author ishaa
 */
public class PatientPrescription extends javax.swing.JFrame {
    int PatientID;
    /**
     * Creates new form PatientPrescription
     */
    public PatientPrescription(int pid) {
        initComponents();
        PatientID = pid;
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital_Management", "root", "!shuB0410");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("""
                           SELECT Prescriptions.Prescription_id, Patients.name AS PatientName, Staff.name AS DoctorName, Appointments.Reason_for_visit, Diseases.Name AS DiseaseName, Prescriptions.medication 
                           FROM Prescriptions 
                           JOIN Patients ON Prescriptions.Patient_ID = Patients.Patient_ID 
                           JOIN Appointments ON Appointments.Patient_id = Patients.Patient_ID 
                           JOIN Prescription_Diseases ON Prescriptions.Prescription_ID = Prescription_Diseases.Prescription_ID 
                           JOIN Diseases ON Prescription_Diseases.Disease_id = Diseases.Disease_ID 
                           JOIN Staff ON Staff.Staff_ID = Appointments.Doctor_ID 
                           WHERE Prescriptions.Patient_ID = """ + PatientID + " and Appointments.Appointment_ID=Prescriptions.Appointment_ID \n" +
                            "ORDER BY Prescriptions.date DESC \n" +
                            "LIMIT 1;");
            if(rs.next()){
                prescriptionID.setText(rs.getString("Prescription_id"));
                Pname.setText(rs.getString("PatientName"));
                Dname.setText(rs.getString("DoctorName"));
                ReasonVisit.setText(rs.getString("Reason_for_visit"));
                DiseasesFound.setText(rs.getString("DiseaseName"));
                Medication.setText(rs.getString("medication"));
            }
        }
        catch(Exception e){
            System.out.println(e.toString());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prescriptionID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Dname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ReasonVisit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DiseasesFound = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Medication = new javax.swing.JLabel();
        return_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Prescription");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 6, 120, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Prescription ID: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 43, 110, 20);

        prescriptionID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prescriptionID.setText("No Data Found");
        getContentPane().add(prescriptionID);
        prescriptionID.setBounds(164, 43, 370, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Patient Name: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 75, 100, 20);

        Pname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pname.setText("No Data Found");
        getContentPane().add(Pname);
        Pname.setBounds(164, 75, 370, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Doctor Name: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(48, 107, 100, 20);

        Dname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dname.setText("No Data Found");
        getContentPane().add(Dname);
        Dname.setBounds(164, 107, 370, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Reason For Visit: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(48, 139, 120, 20);

        ReasonVisit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReasonVisit.setText("No Data Found");
        getContentPane().add(ReasonVisit);
        ReasonVisit.setBounds(166, 139, 370, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Diseases Found: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(48, 171, 120, 20);

        DiseasesFound.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DiseasesFound.setText("No Data Found");
        getContentPane().add(DiseasesFound);
        DiseasesFound.setBounds(163, 171, 370, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Medication: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(48, 203, 90, 20);

        Medication.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Medication.setText("No Data Found");
        getContentPane().add(Medication);
        Medication.setBounds(163, 203, 370, 20);

        return_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        return_btn.setText("Return to Menu");
        return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btnActionPerformed(evt);
            }
        });
        getContentPane().add(return_btn);
        return_btn.setBounds(222, 251, 140, 27);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-90, 0, 700, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btnActionPerformed
        // TODO add your handling code here:
        PatientMenu pm = new PatientMenu(PatientID);
        pm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_return_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PatientPrescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiseasesFound;
    private javax.swing.JLabel Dname;
    private javax.swing.JLabel Medication;
    private javax.swing.JLabel Pname;
    private javax.swing.JLabel ReasonVisit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel prescriptionID;
    private javax.swing.JButton return_btn;
    // End of variables declaration//GEN-END:variables
}
