/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;

/**
 *
 * @author ishaa
 */
public class PatientMenu extends javax.swing.JFrame {
    int PatientID;
    /**
     * Creates new form PatientMenu
     */
    public PatientMenu(int pid) {
        initComponents();
        PatientID = pid;
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital_Management", "root", "!shuB0410");
            Statement s = con.createStatement();
            String name = "";
            ResultSet rs = s.executeQuery("SELECT name FROM Patients WHERE Patient_ID=" + pid);
            if (rs.next()) {
                name = rs.getString("name");
            }
            else{
                System.out.println("Error while retrieving data");
            }
            
            DisName.setText("Hello, " + name);
            DisPID.setText("PatientID: " + PatientID);
            
        }   
        catch(Exception e){
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisName = new javax.swing.JLabel();
        DisPID = new javax.swing.JLabel();
        appointment_book = new javax.swing.JButton();
        result_check = new javax.swing.JButton();
        prescription_check = new javax.swing.JButton();
        bill_check = new javax.swing.JButton();
        allergy_view = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        unreg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 420));
        getContentPane().setLayout(null);

        DisName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DisName.setText("Hello, Name");
        getContentPane().add(DisName);
        DisName.setBounds(29, 52, 280, 25);

        DisPID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DisPID.setText("PatientID: ");
        getContentPane().add(DisPID);
        DisPID.setBounds(356, 52, 180, 25);

        appointment_book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        appointment_book.setText("Book an Appointment");
        appointment_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointment_bookActionPerformed(evt);
            }
        });
        getContentPane().add(appointment_book);
        appointment_book.setBounds(139, 108, 270, 27);

        result_check.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        result_check.setText("Check Latest Test Results");
        result_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_checkActionPerformed(evt);
            }
        });
        getContentPane().add(result_check);
        result_check.setBounds(139, 147, 270, 27);

        prescription_check.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prescription_check.setText("Latest Prescription");
        prescription_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescription_checkActionPerformed(evt);
            }
        });
        getContentPane().add(prescription_check);
        prescription_check.setBounds(139, 186, 270, 27);

        bill_check.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bill_check.setText("Check Latest Bill");
        bill_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_checkActionPerformed(evt);
            }
        });
        getContentPane().add(bill_check);
        bill_check.setBounds(139, 225, 270, 27);

        allergy_view.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        allergy_view.setText("View or Update Allergies");
        allergy_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergy_viewActionPerformed(evt);
            }
        });
        getContentPane().add(allergy_view);
        allergy_view.setBounds(139, 264, 270, 27);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("APOLLO HOSPITALS PVT. LTD.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(103, 14, 341, 32);

        unreg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unreg.setText("UnRegister as Patient");
        unreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unregActionPerformed(evt);
            }
        });
        getContentPane().add(unreg);
        unreg.setBounds(139, 303, 270, 27);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(139, 342, 270, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/istockphoto-940993008-612x612.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMinimumSize(new java.awt.Dimension(550, 390));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 590, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appointment_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointment_bookActionPerformed
        // TODO add your handling code here:
        AppointmentBooking apb = new AppointmentBooking(PatientID);
        apb.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_appointment_bookActionPerformed

    private void result_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_checkActionPerformed
        // TODO add your handling code here:
        latestTestResults ltr = new latestTestResults(PatientID);
        ltr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_result_checkActionPerformed

    private void prescription_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescription_checkActionPerformed
        // TODO add your handling code here:
        PatientPrescription pp = new PatientPrescription(PatientID);
        pp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_prescription_checkActionPerformed

    private void bill_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_checkActionPerformed
        // TODO add your handling code here:
        PatientBill pb = new PatientBill(PatientID);
        pb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bill_checkActionPerformed

    private void allergy_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergy_viewActionPerformed
        // TODO add your handling code here:
        PatientAllergies pa = new PatientAllergies(PatientID);
        pa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_allergy_viewActionPerformed

    private void unregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unregActionPerformed
        // TODO add your handling code here:
        UnRegistrationForm urf = new UnRegistrationForm(PatientID);
        urf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_unregActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PatientLogin pl = new PatientLogin();
        pl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PatientMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisName;
    private javax.swing.JLabel DisPID;
    private javax.swing.JButton allergy_view;
    private javax.swing.JButton appointment_book;
    private javax.swing.JButton bill_check;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton prescription_check;
    private javax.swing.JButton result_check;
    private javax.swing.JButton unreg;
    // End of variables declaration//GEN-END:variables
}
