/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
/**
 *
 * @author ishaa
 */
public class PatientRegistration extends javax.swing.JFrame {

    /**
     * Creates new form PatientRegistration
     */
    public PatientRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LName = new javax.swing.JTextField();
        LAge = new javax.swing.JTextField();
        LBmi = new javax.swing.JTextField();
        register_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        LDay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        LMonth = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LYear = new javax.swing.JTextField();
        Error = new javax.swing.JLabel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Patient Registration Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 240, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Enter Patient DOB");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 150, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Enter Patient Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 150, 150, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Enter Patient Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 40, 160, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Enter Patient Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 200, 170, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Enter Patient BMI");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 240, 150, 25);

        LName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LName.setToolTipText("Name");
        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });
        getContentPane().add(LName);
        LName.setBounds(190, 50, 210, 26);

        LAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAgeActionPerformed(evt);
            }
        });
        getContentPane().add(LAge);
        LAge.setBounds(170, 150, 260, 30);

        LBmi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBmiActionPerformed(evt);
            }
        });
        getContentPane().add(LBmi);
        LBmi.setBounds(170, 240, 260, 26);

        register_btn.setText("Register");
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });
        getContentPane().add(register_btn);
        register_btn.setBounds(130, 290, 180, 42);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("DD");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 80, 30, 20);

        LDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(LDay);
        LDay.setBounds(350, 110, 70, 26);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("YYYY");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 80, 40, 20);

        LMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(LMonth);
        LMonth.setBounds(270, 110, 50, 26);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("MM");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 80, 40, 20);

        LYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(LYear);
        LYear.setBounds(180, 110, 70, 26);

        Error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Error.setForeground(new java.awt.Color(255, 51, 51));
        Error.setText("   ");
        getContentPane().add(Error);
        Error.setBounds(10, 340, 343, 20);

        genderGrp.add(rdoMale);
        rdoMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoMale.setText("Male");
        rdoMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rdoMale);
        rdoMale.setBounds(200, 200, 90, 25);

        genderGrp.add(rdoFemale);
        rdoFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoFemale.setText("Female");
        getContentPane().add(rdoFemale);
        rdoFemale.setBounds(350, 200, 100, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/istockphoto-940993008-612x612.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 590, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void LAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAgeActionPerformed

    private void LBmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LBmiActionPerformed

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital_Management", "root", "!shuB0410");
            Statement s = con.createStatement();
            String Name = LName.getText();
            String yyyy = LYear.getText();
            String mm = LMonth.getText();
            String dd = LDay.getText();
            String age = LAge.getText();
            String gender = "";
            String BMI = LBmi.getText();
            String DOB = yyyy + "-" + mm + "-" + dd;
            
            if(rdoMale.isSelected()){
                gender = "Male";
            }
            else if(rdoMale.isSelected()){
                gender = "Female";
            }
            else{
                Error.setText("Please select Gender");
                return;
            }
            
            // Chekcing if DOB entered is correct or not.
            try{
                LocalDate.parse(DOB);
            }
            catch(DateTimeParseException e){
                Error.setText("Please enter a valid date (YYYY-MM-DD)");
                System.out.println("Please enter a valid date (YYYY-MM-DD)");
                return;
            }
            
            String checkQuery = "SELECT * FROM Patients WHERE Name = '" + Name + "' AND DOB = '" + DOB + "'"; 
            ResultSet existingPatients = s.executeQuery(checkQuery);
            if (existingPatients.next()) {
                Error.setText("Patient with the same name and DOB already exists.");
                System.out.println("Patient with the same name and DOB already exists.");
                return; // Exit the method
            }
            
            
            if(!Name.isEmpty() && !DOB.isEmpty() && !age.isEmpty() && !gender.isEmpty() && !BMI.isEmpty()){
                String query = "INSERT INTO Patients (Name, DOB, Age, Gender, BMI) VALUES ('" + Name + "', '" + DOB + "', " + age + ", '" + gender + "', " + BMI + ")";
                s.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
                ResultSet key = s.getGeneratedKeys();
                key.next();
                RegisteredSuccessfully rs = new RegisteredSuccessfully(Name, key.getInt(1));
                rs.setVisible(true);
                this.setVisible(false);
                
            }
            else{
                Error.setText("Please enter all fields");
                System.out.println("Please enter all fields");
            }
        }
        catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_register_btnActionPerformed

    private void rdoMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error;
    private javax.swing.JTextField LAge;
    private javax.swing.JTextField LBmi;
    private javax.swing.JTextField LDay;
    private javax.swing.JTextField LMonth;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField LYear;
    private javax.swing.ButtonGroup genderGrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JButton register_btn;
    // End of variables declaration//GEN-END:variables
}
